import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';
import { getClientIp, rateLimit } from '@/lib/security/rateLimit';

export async function POST(request: Request) {
  try {
    const ip = getClientIp(request);
    const limitResult = rateLimit({ key: `notify:${ip}`, limit: 5, windowMs: 60_000 });
    if (!limitResult.allowed) {
      return NextResponse.json(
        { success: false, error: 'Too many requests' },
        { status: 429, headers: { 'Retry-After': String(limitResult.retryAfterSeconds) } }
      );
    }

    const body = await request.json();
    const { to, subject, text, html } = body;
    if (!to) {
      return NextResponse.json({ success: false, error: 'Recipient is required' }, { status: 400 });
    }

    const smtpHost = process.env.SMTP_HOST;
    const smtpPort = process.env.SMTP_PORT ? Number(process.env.SMTP_PORT) : undefined;
    const smtpUser = process.env.SMTP_USER;
    const smtpPass = process.env.SMTP_PASS;
    const smtpSecure = process.env.SMTP_SECURE === 'true';
    const fromAddress = process.env.SMTP_FROM || smtpUser;

    if (!smtpHost || !smtpPort || !smtpUser || !smtpPass || !fromAddress) {
      return NextResponse.json({ success: false, error: 'Notification service not configured' }, { status: 500 });
    }

    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: smtpPort,
      secure: smtpSecure,
      auth: {
        user: smtpUser,
        pass: smtpPass,
      },
    });

    const info = await transporter.sendMail({
      from: fromAddress,
      to,
      subject: subject || 'New System Alert - INTEL TRADER',
      text: text || 'A new alert has been generated by the INTEL TRADER system.',
      html: html || `<b>${text || 'A new alert has been generated by the INTEL TRADER system.'}</b>`,
    });

    return NextResponse.json({ success: true, messageId: info.messageId });
  } catch (error) {
    console.error('Failed to send email notification:', error);
    return NextResponse.json(
      { success: false, error: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    );
  }
}
