import { NextResponse } from 'next/server';
import { getClientIp, rateLimit } from '@/lib/security/rateLimit';
import { sendEmail } from '@/lib/mail';

export async function POST(request: Request) {
  try {
    const ip = getClientIp(request);
    const limitResult = rateLimit({ key: `notify:${ip}`, limit: 5, windowMs: 60_000 });
    if (!limitResult.allowed) {
      return NextResponse.json(
        { success: false, error: 'Too many requests' },
        { status: 429, headers: { 'Retry-After': String(limitResult.retryAfterSeconds) } }
      );
    }

    const body = await request.json();
    const { to, subject, text, html } = body;
    if (!to) {
      return NextResponse.json({ success: false, error: 'Recipient is required' }, { status: 400 });
    }

    const info = await sendEmail({
      to,
      subject: subject || 'New System Alert - INTEL TRADER',
      text: text || 'A new alert has been generated by the INTEL TRADER system.',
      html: html || `<b>${text || 'A new alert has been generated by the INTEL TRADER system.'}</b>`,
    });

    return NextResponse.json({ success: true, messageId: info.messageId });
  } catch (error) {
    console.error('Failed to send email notification:', error);
    return NextResponse.json(
      { success: false, error: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    );
  }
}
